export const FETCH_NEXT_POST_STARTED = 'FETCH_NEXT_POST_STARTED';
export const FETCH_NEXT_POST_SUCCESS = 'FETCH_NEXT_POST_SUCCESS';
export const FETCH_NEXT_POST_FAILURE = 'FETCH_NEXT_POST_FAILURE';
export const SHOW_PREVIOUS_POST = 'SHOW_PREVIOUS_POST';
export const SHOW_NEXT_POST = 'SHOW_NEXT_POST';
export const SHOW_NEXT_SUBPOST = 'SHOW_NEXT_SUBPOST';
export const SHOW_PREVIOUS_SUBPOST = 'SHOW_PREVIOUS_SUBPOST';
